-- Drop existing tables if needed (uncomment to wipe completely):
-- DROP TABLE IF EXISTS order_items;
-- DROP TABLE IF EXISTS payments;
-- DROP TABLE IF EXISTS orders;
-- DROP TABLE IF EXISTS menu;
-- DROP TABLE IF EXISTS tables;

-- 1. Create MENU Table
CREATE TABLE menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  available BOOLEAN DEFAULT TRUE
);

-- 2. Create ORDERS Table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_number INT NOT NULL,
  source TEXT NOT NULL, -- 'QR' or 'POS'
  status TEXT NOT NULL DEFAULT 'NEW', -- 'NEW', 'ACCEPTED', 'COOKING', 'READY', 'SERVED', 'CLOSED'
  total NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create ORDER_ITEMS Table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  menu_id BIGINT REFERENCES menu(id),
  name TEXT NOT NULL,
  quantity INT NOT NULL,
  price NUMERIC NOT NULL
);

-- 4. Create PAYMENTS Table
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  method TEXT NOT NULL, -- 'cash', 'upi', 'card'
  amount NUMERIC NOT NULL,
  time TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create TABLES Table
CREATE TABLE tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_number INT NOT NULL UNIQUE,
  qr_code TEXT NOT NULL
);

-- Insert MENU Seed Data
INSERT INTO menu (name, category, price, available) VALUES
  ('Paal Pathiri & Beef', 'Special Combos', 150, true),
  ('Ghee Rice & Varutharacha Curry', 'Special Combos', 160, true),
  ('Paal Puttu & Chicken', 'Special Combos', 140, true),
  
  ('Tea', 'Hot Beverages', 15, true),
  ('Black Tea', 'Hot Beverages', 10, true),
  ('Coffee', 'Hot Beverages', 20, true),
  ('Boost', 'Hot Beverages', 25, true),
  ('Horlicks', 'Hot Beverages', 25, true),
  ('Lemon Tea', 'Hot Beverages', 15, true),
  ('Honey Lemon Tea', 'Hot Beverages', 25, true),
  
  ('Banana Fry', 'Snacks', 15, true),
  ('Chicken Samosa', 'Snacks', 25, true),
  ('Erachi Pathiri', 'Snacks', 20, true),
  ('Onion Pakkavada', 'Snacks', 15, true),
  
  ('Strawberry Shake', 'Juices', 80, true),
  ('Mango Shake', 'Juices', 80, true),
  ('Oreo Shake', 'Juices', 90, true),
  ('Sharjah Shake', 'Juices', 90, true),
  ('Apple Juice', 'Juices', 70, true),
  ('Pineapple Juice', 'Juices', 60, true),
  ('Anar Juice', 'Juices', 80, true),
  ('Anar Pure Juice', 'Juices', 100, true),
  ('Avocado Juice', 'Juices', 110, true),
  ('Grape Juice', 'Juices', 60, true),
  ('Tender Coconut', 'Juices', 50, true),
  ('Citrus Juice', 'Juices', 40, true),
  ('Watermelon Juice', 'Juices', 50, true),
  
  ('Ayakoora Curry (Seer Fish)', 'Fish Mains (Seasonal Rate)', 200, true),
  ('Fish Moli (Seer Fish)', 'Fish Mains (Seasonal Rate)', 220, true),
  ('Ayakoora Fry', 'Fish Mains (Seasonal Rate)', 250, true),
  ('Avoli Fry (Pomfret)', 'Fish Mains (Seasonal Rate)', 250, true),
  ('Chemmeen Fry (Prawns)', 'Fish Mains (Seasonal Rate)', 220, true),
  ('Karimeen Fry (Pearl Spot)', 'Fish Mains (Seasonal Rate)', 300, true),
  ('Kadukka Kandari Fry', 'Fish Mains (Seasonal Rate)', 180, true),
  ('Ayakoora Pollichathu', 'Fish Mains (Seasonal Rate)', 280, true),
  ('Avoli Pollichathu', 'Fish Mains (Seasonal Rate)', 280, true),
  ('Karimeen Pollichathu', 'Fish Mains (Seasonal Rate)', 350, true),
  
  ('Beef Roast', 'Beef Specials', 160, true),
  ('Beef Varattiyathu', 'Beef Specials', 160, true),
  ('Beef Masala', 'Beef Specials', 160, true),
  ('Beef Brain', 'Beef Specials', 180, true),
  ('Beef Curry', 'Beef Specials', 150, true),
  ('Beef Kondattam', 'Beef Specials', 170, true),
  ('Beef Stew', 'Beef Specials', 160, true),
  ('Beef Kandari', 'Beef Specials', 170, true),
  
  ('Gobi Manchurian', 'Vegetarian', 120, true),
  ('Chilly Gobi', 'Vegetarian', 120, true),
  ('Gobi 65', 'Vegetarian', 130, true),
  ('Chilly Paneer', 'Vegetarian', 160, true),
  ('Paneer 65', 'Vegetarian', 160, true),
  ('Mushroom Masala', 'Vegetarian', 150, true),
  ('Chilly Mushroom', 'Vegetarian', 150, true),
  ('Mushroom 65', 'Vegetarian', 150, true),
  ('Tomato Fry', 'Vegetarian', 100, true),
  
  ('Chicken Curry', 'Chicken Specials', 150, true),
  ('Pidi Kozhi Fry', 'Chicken Specials', 250, true),
  ('Chutta Kozhi', 'Chicken Specials', 220, true),
  ('Chutta Kozhi Kandari', 'Chicken Specials', 230, true),
  ('Chicken Pepper Roast', 'Chicken Specials', 180, true),
  ('Chicken Pepper Fry', 'Chicken Specials', 180, true),
  ('Chicken Kondattam', 'Chicken Specials', 190, true),
  ('Chicken Masala', 'Chicken Specials', 170, true),
  ('Chicken Fry', 'Chicken Specials', 140, true),
  
  ('Mutton Kuruma', 'Mutton Specials', 250, true),
  ('Mutton Pepper Roast', 'Mutton Specials', 280, true),
  ('Mutton Pepper Fry', 'Mutton Specials', 280, true),
  ('Mutton Chops', 'Mutton Specials', 260, true),
  
  ('Chicken Biriyani', 'Meals & Rice', 180, true),
  ('Ghee Rice', 'Meals & Rice', 100, true),
  ('Kappa', 'Meals & Rice', 80, true),
  ('Meals', 'Meals & Rice', 100, true),
  
  ('Porotta', 'Bread Items', 15, true),
  ('Nei Pathiri', 'Bread Items', 20, true),
  ('Kunji Pathiri', 'Bread Items', 20, true),
  ('Puttu', 'Bread Items', 40, true),
  ('Cheratta Puttu', 'Bread Items', 30, true),
  ('Trachi Puttu', 'Bread Items', 60, true);

-- Insert TABLES Seed Data
-- Generating tables 1 to 20 with dummy QR links (can be modified later)
INSERT INTO tables (table_number, qr_code) VALUES
  (1, 'https://restaurant.com/menu?table=1'),
  (2, 'https://restaurant.com/menu?table=2'),
  (3, 'https://restaurant.com/menu?table=3'),
  (4, 'https://restaurant.com/menu?table=4'),
  (5, 'https://restaurant.com/menu?table=5'),
  (6, 'https://restaurant.com/menu?table=6'),
  (7, 'https://restaurant.com/menu?table=7'),
  (8, 'https://restaurant.com/menu?table=8'),
  (9, 'https://restaurant.com/menu?table=9'),
  (10, 'https://restaurant.com/menu?table=10');
